### PR TITLE
Helm packages and more

### PR DESCRIPTION
**Pull request by Eddman**
- S3 bucket to transfer startup addons
 - Lambda
 - Cloud init config
 - Multi worker nodes
 - Fixed fully qualified hostname
 - Helm packages
 - Calico replaced by Weave
 - etc.

### CODE REVIEW

**Comment by scholzj** [comment]
Sorry guys ... too many things in single PR. Hard to pick one, hard to review. But thanks for trying :-)

**Comment by Eddman** [comment]
Just use it as inspiration whenever you have time. At least the hostname fix is worth taking 😉

**Comment by scholzj** [comment]
@Eddman  You had any problems with hostname -f?

**Comment by Eddman** [comment]
@scholzj  it is not working unless AWS sets the fully qualified hostname first. In reality this occures from time to time and kubeadm is unable to finish. The only way to always gat the correct one is by calling the REST endpoint.

**Comment by scholzj** [comment]
@Eddman Ok, good point, makes sense. I will have a look at it when I rework this into Terrafor module.

**BTW:** ideally it should probably also not be set as the hostname but just [passed to kubeadm](https://github.com/scholzj/terraform-aws-minikube/blob/master/scripts/init-aws-minikube.sh#L64)

**Pull request closed without merging**
